### ISSUE TITLE
Unable to open and run the project

### ISSUE THREAD

**Issue by poonam-tru** [ninetailed-inc/ninetailed-examples#39]
I have done all the steps, after that when i am trying to run the project, Its showing the config error.

**Comment by poonam-tru** [comment]
![image_2023_08_11T10_31_54_613Z](https://github.com/ninetailed-inc/ninetailed-examples/assets/59247001/7f7e7398-c905-4515-98ef-c2db91853fe0)
![image_2023_08_11T10_33_42_757Z](https://github.com/ninetailed-inc/ninetailed-examples/assets/59247001/c1496f51-53dd-47e1-ac75-b7ab7aae28f1)

* Steps - When I am running the command 'yarn dev" , the above error occurs.
Can you please look into this?

**Comment by BraunreutherA** [comment]
Hi @poonam-tru, we've done an update to the content and content type imports. I hope this helps!

**Comment by cwkosman** [comment]
Demo content export updated to include the `config` and `setting` content types.
