### ISSUE TITLE
[README] all-in example points to wrong demo

### ISSUE THREAD

**Issue by DanweDE** [ninetailed-inc/ninetailed-examples#78]
I believe your `marketing-contentful-next-app-all-in` example is pointing to the wrong live demo.

I assume the right demo would be https://examples-marekting-contentful-next-app-all-in.vercel.app/ (see mentioned [in docs on your website](https://docs.ninetailed.io/for-developers/experience-sdk/esr-and-ssr)) but the all-in [README.md](https://github.com/ninetailed-inc/ninetailed-examples/blob/main/marketing-contentful-next-app-all-in/README.md) is currently pointing to [https://b2b.demo.ninetailed.io/](https://b2b.demo.ninetailed.io/).

**Comment by cwkosman** [comment]
READMEs and Vercel deploy buttons should now be pointing at the correct URLs. Please confirm.

**Comment by DanweDE** [comment]
Thank you, seems to be all wired up now :+1:

**Comment by DanweDE** [comment]
Thank you, seems to be all wired up now 👍
